### ISSUE TITLE
License terms broken from RinCheat !

### ISSUE THREAD

**Issue by CelesteBlue-dev** [Finalcheat/PSVITA-CHEAT#1]
Either release src code and give credits to Rinnegatamante
or your github will be closed for license terms break.
Regards.

**Comment by Finalcheat** [comment]
I am not using RinCheat source code.

**Comment by joel16** [comment]
@CelesteBlue-dev Rinnegatmate hasn't provided enough evidence to prove this person is using his code. One function call doesn't do any justice. The second image on his twitter doesn't mean anything either.

Please correct me if I'm wrong. I'm not a fan of people who steal licensed code and I'm 100% against breaking the license, but you can't just force this without providing **concrete** evidence.

**Comment by GregoryRasputin** [comment]
I totally agree joel16, he did exactly the same thing with Team OneLua with zero proof and just a bunch of assumptions.
You cannot claim to care for the community and continuously attack the competition.

Not sure which is worse the zero proof of the fact Rin is blaming this dev on him stopping work on a Homebrew he hasn't really been updating himself >.<

**Comment by Rinnegatamante** [comment]
@GregoryRasputin @joel16 https://twitter.com/Rinnegatamante/status/909098376708444161 Hope it's enough a RE of that plugin just to prove I WAS RIGHT. You really think i start talking whitout having idea of what i fucking say?

Thanks for having called me a liar,i love you both too.

**Comment by joel16** [comment]
@Rinnegatamante I told you politely that your previous tweet did not provide enough evidence, I never said I didn't believe you, or did I ever call you a 'liar'. I just wanted concrete proof before jumping into conclusions. So why the fuck are you putting words in my mouth? Maybe the other guy did, but I certainly didn't.

PS. This is the

**Comment by CelesteBlue-dev** [comment]
@joel16 putting a dislike on my post is not a good idea because I HAD to post this ISSUE because it is an issue, even if later the issue is avered wrong so the issue is closed.

**Comment by joel16** [comment]
Actually @CelesteBlue-dev I wasn't on anyone's side. I chose  dislike because you created an issue without concrete evidence. If you guys did create this issue just now with the evidence you gathered recently, I would surely side with you as you are on the right here. I was merely just waiting for concrete evidence, because there are many times when developers choose the same function names, it could have just been a coincidence, but either way you're right. I congratulate you for talking your time out to reverse this, do proceed with whatever action you guys are depending on taking.

**Comment by CelesteBlue-dev** [comment]
@joel16 ok in fact I realize that it's gregory's post that is provocating Rinnegatamante.
I am thinking like you but what I would like the most would be this VitaCheat to become open source.
Please @Finalcheat for the scene.

**Comment by Rinnegatamante** [comment]
@joel16 The liar part was referred to @GregoryRasputin , i just miswrote or badly wrote my sentence, my apologize.

**Comment by nmagod** [comment]
You know the fastest way to prove them wrong would be to release the source, so do it.

**Comment by Rinnegatamante** [comment]
He can't prove me wrong. I reversed the suprx available for download. If he releases the source and shows different code it means he edited it on purpose. @nmagod .
He fucked up, dot.

**Comment by joel16** [comment]
I tried to give you a chance @Finalcheat but seems like you fucked up. You **have** to release the source now, or this can be taken down due to violation.
