### ISSUE TITLE
Work or not ?

### ISSUE THREAD

**Issue by Douman972** [Finalcheat/PSVITA-CHEAT#4]
Hello,

First of all bravo for this application easy to use and very fast to scan memory.
I tried PSVITA-CHEAT on two games and it worked partially.
On "Flying Hamster" I did a simple search and found addresses for life and the weapon bar but as soon as we change level the codes no longer work and I have to search again the corresponding addresses To life and weapon bar.

On "Do not Starve" I did simple searches for items but when I change the value it does not take effect.

Is there something I have done wrong?
From the console, can a code be enabled by default. In front of the name of my code I have _V0 and directly on the console I can not get it to _V1?
What is the "cross memory" section for?
Will there be a new version soon?
Will you soon provide a translation of the file "PSVITACHEATv360.z02Beta_20170630.pdf" and could you leave the possibility of printing?

cordially

**Comment by Finalcheat** [comment]
> First of all bravo for this application easy to use and very fast to scan memory.
I tried PSVITA-CHEAT on two games and it worked partially.
On "Flying Hamster" I did a simple search and found addresses for life and the weapon bar but as soon as we change level the codes no longer work and I have to search again the corresponding addresses To life and weapon bar.
On "Do not Starve" I did simple searches for items but when I change the value it does not take effect.

default search range is 0x81000000-0x83000000, you can try expanding search range.

> From the console, can a code be enabled by default. In front of the name of my code I have _V0 and directly on the console I can not get it to _V1?

_V1 mean default enable. You can change _V0 to _V1 using plain text editing software.

> What is the "cross memory" section for?

dump memory and import memory.

> Will there be a new version soon?

Yes. maybe next week.

> Will you soon provide a translation of the file "PSVITACHEATv360.z02Beta_20170630.pdf" and could you leave the possibility of printing?

I was been busy these days, have no time to do the english manual.

**Comment by Douman972** [comment]
Thank you for your answers. Indeed by expanding my search between 0x81000000 and 0x93000000 I got memory addresses that work. But be careful not to look below address 0x81000000 otherwise it crash.
Nevertheless every time I restart the game or the console the memory address corresponding to the cheat previously found is no longer the same.

Do you know why ?
Is there a way to put a relative address?
Or to ensure that the game always occupies the same range of address?
In this case, is the cross-memory menu useful?
If so, how to use it?

**Comment by Finalcheat** [comment]
some game address is dynamic, you need to find pointers.

**Comment by Douman972** [comment]
Is it possible with your program ?
If yes, how can I do it ?

**Comment by phonzeh** [comment]
Just perform RAM dumps and use a third party pointer searcher tool in your computer to narrow down and hope it's only 1 level deep.

There was a psp pointer searching tool I use to use, you could probably Google and find.

**Comment by Douman972** [comment]
thank you.
i found a program called TempAR, i don't know how to use it. i'll search. 
I'm interest if you remember the name of the program you used. 
I'm interest too if finalcheat have an idea.

**Comment by kingknuts** [comment]
I'm using tempar and is not usable, the adresses are too high for the program.
